services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysqldb
    command: --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance_manager
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_secure123_password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  api:
    build: .
    container_name: finance_manager_api
    environment:
      DB_HOST: db
      DB_USER: api_user
      DB_PASS: api_secure123_password123
      DB_NAME: finance_manager
    ports:
      - "9090:9099"


volumes:
  db_data: